spring:
  application:
      name: "wind-auth-svc"
  datasource:
    url: jdbc:mysql://mysql:3306/wind_auth?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  context-path: "/auth/svc"
  port: 8080
